In [1]:
from numpy import * as np

SyntaxError: invalid syntax (<ipython-input-1-157140e7bde7>, line 1)

In [2]:
import numpy as np

In [3]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


# 这是numpy学习笔记


## 1.数组的创建

In [ ]:
# a = np.array([1, 2, 3])

In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
a1 = np.arange(15)

In [8]:
print(type(a1))
print(a1)

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [9]:
print(a1.dtype)

int32


In [10]:
a2 = np.array(range(10), dtype="i8")

In [11]:
print(a2.dtype)

int64


In [12]:
a3 = np.array([1,0,1,0,1,0],dtype="bool" )  # 指定类型

In [13]:
print(a3)

[ True False  True False  True False]


In [14]:
a4 = a3.astype("int8")  # 调整类型

In [15]:
print(a4)

[1 0 1 0 1 0]


In [16]:
a5 = np.array([random.random() for i in range(10)])  # 生成小数数组

In [17]:
print(a5)

[0.30624354 0.15805669 0.24917197 0.15848761 0.52974618 0.27012424
 0.42383294 0.32721137 0.47537906 0.49577152]


In [18]:
a6 = np.round(a5, 2)  # 取小数点后两位

In [19]:
print(a6)

[0.31 0.16 0.25 0.16 0.53 0.27 0.42 0.33 0.48 0.5 ]


## 2.数组的形状

In [1]:
t1 = np.arange(10)

NameError: name 'np' is not defined

In [2]:
import numpy as np


In [3]:
t1 = np.arange(10)  # 一维数组

In [4]:
t1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
t1.shape

(10,)

In [6]:
t2 = np.array([[1,2,3],[4,5,6]])  # 二维数组

In [7]:
t2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
t2.shape

(2, 3)

In [9]:
t3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])  # 三维数组

In [10]:
t3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [11]:
t3.shape

(2, 2, 3)

In [12]:
t4 = np.arange(12)

In [13]:
t4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
t4.reshape(3,4)  # 调整数据形状

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
t5 = np.arange(24).reshapeh(2,3,4)

AttributeError: 'numpy.ndarray' object has no attribute 'reshapeh'

In [20]:
t5 = np.arange(24).reshape((2,3,4))

In [21]:
t5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [19]:
t5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [22]:
t5.reshape((24,)) # shape中有几个值就是几维

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
t5.reshape((24,1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [24]:
t5.reshape((1,24))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [25]:
t5.shape[0]

2

In [26]:
t5 = t6.reshape((3,4))

NameError: name 't6' is not defined

In [29]:
t5 = t5.reshape((4,6))
t5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [30]:
t5.flatten()
t5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [31]:
t5.flatten()  # 展开数组成一维数组


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## 3.数组的计算

In [33]:
t5+2

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25]])

In [35]:
t5/0  # 不会报错 nan:not a number  inf: infinity


E:\Aoconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
E:\Aoconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [36]:
t6 = np.arange(100,124).reshape((4,6))
t6

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123]])

In [37]:
t5+t6


array([[100, 102, 104, 106, 108, 110],
       [112, 114, 116, 118, 120, 122],
       [124, 126, 128, 130, 132, 134],
       [136, 138, 140, 142, 144, 146]])

In [39]:
t7 = np.arange(6)
t7

array([0, 1, 2, 3, 4, 5])

In [40]:
t5-t7

array([[ 0,  0,  0,  0,  0,  0],
       [ 6,  6,  6,  6,  6,  6],
       [12, 12, 12, 12, 12, 12],
       [18, 18, 18, 18, 18, 18]])

In [41]:
t8 = np.arange(4).reshape((4,1))
t8

array([[0],
       [1],
       [2],
       [3]])

## 4.数组转置 

In [50]:
t5.shape



(4, 6)

In [53]:
t5=t5.transpose()
t5.shape

(6, 4)

In [54]:
t5 = t5.T
t5.shape

(4, 6)

In [55]:
t5 = t5.swapaxes(1,0)
t5.shape

(6, 4)

## 5.numpy读取数据:
```np.loadtxt(frame.dtype=np.float.delimiter=None,skiprows=0,usecols=None,unpack=False)```




| 参数 | 解释 |
|--|--|
| frame    | 文件，字符串，产生器，可以是.gz或.bz2压缩文件 |
| dtype    | 数据类型，可选，CSV的字符以什么数据类型读入数组中，默认np.float |
| delimiter | 分离字符串,默认是任何空格,改为逗号|
| skiprows  | 跳过前x行,一般跳过表头 |
| usecols   | 读取指定的列,索引,元组类型 |
| unpack   | 如果是True,读入属性将分别写入不同的数组变量,False读入数据只写入一个数组变量,默认False |


In [1]:
import numpy as np

In [2]:
us_file_path = "./youtube_video_data/US_video_data_numbers.csv"
uk_file_path = "./youtube_video_data/GB_video_data_numbers.csv"
t1 = np.loadtxt(us_file_path,delimiter=",")
print(t1)

[[4.394029e+06 3.200530e+05 5.931000e+03 4.624500e+04]
 [7.860119e+06 1.858530e+05 2.667900e+04 0.000000e+00]
 [5.845909e+06 5.765970e+05 3.977400e+04 1.707080e+05]
 ...
 [1.424630e+05 4.231000e+03 1.480000e+02 2.790000e+02]
 [2.162240e+06 4.103200e+04 1.384000e+03 4.737000e+03]
 [5.150000e+05 3.472700e+04 1.950000e+02 4.722000e+03]]


In [3]:
t1 = np.loadtxt(us_file_path,delimiter=",", dtype="int")
print(t1)

[[4394029  320053    5931   46245]
 [7860119  185853   26679       0]
 [5845909  576597   39774  170708]
 ...
 [ 142463    4231     148     279]
 [2162240   41032    1384    4737]
 [ 515000   34727     195    4722]]


In [4]:
t1 = np.loadtxt(us_file_path,delimiter=",", dtype="int",unpack=True)
print(t1)

[[4394029 7860119 5845909 ...  142463 2162240  515000]
 [ 320053  185853  576597 ...    4231   41032   34727]
 [   5931   26679   39774 ...     148    1384     195]
 [  46245       0  170708 ...     279    4737    4722]]


## 5.numpy中的索引与切片

In [6]:
t2 = np.loadtxt(us_file_path,delimiter=",",dtype="int")
t2

array([[4394029,  320053,    5931,   46245],
       [7860119,  185853,   26679,       0],
       [5845909,  576597,   39774,  170708],
       ...,
       [ 142463,    4231,     148,     279],
       [2162240,   41032,    1384,    4737],
       [ 515000,   34727,     195,    4722]])

In [7]:
print(t2[2])  #取行

[5845909  576597   39774  170708]


In [9]:
print(t2[2:])  # 取连续多行

[[5845909  576597   39774  170708]
 [2642103   24975    4542   12829]
 [1168130   96666     568    6666]
 ...
 [ 142463    4231     148     279]
 [2162240   41032    1384    4737]
 [ 515000   34727     195    4722]]


In [10]:
print(t2[[1,2,3]])

[[7860119  185853   26679       0]
 [5845909  576597   39774  170708]
 [2642103   24975    4542   12829]]


In [11]:
print(t2[1,:])

[7860119  185853   26679       0]


In [15]:
print(t2[1:2,:])

[[7860119  185853   26679       0]]


In [13]:
print(t2[:,1])  # 取列

[320053 185853 576597 ...   4231  41032  34727]


In [14]:
print(t2[:,2:])

[[  5931  46245]
 [ 26679      0]
 [ 39774 170708]
 ...
 [   148    279]
 [  1384   4737]
 [   195   4722]]


In [16]:
print(t2[[:,1,2,3]])

SyntaxError: invalid syntax (<ipython-input-16-de1cb232fc68>, line 1)

In [17]:
print(t2[:,[1,2,3]])

[[320053   5931  46245]
 [185853  26679      0]
 [576597  39774 170708]
 ...
 [  4231    148    279]
 [ 41032   1384   4737]
 [ 34727    195   4722]]


In [18]:
print(t2[[1,2],[1,2]])  # 取不同位置的点点的坐标为（1，1）（2，2）

[185853  39774]


In [19]:
print(t2[[1,2],[1,2,3]])

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [20]:
print(t2[[1,:],[1,2]])

SyntaxError: invalid syntax (<ipython-input-20-b6c02c0a7726>, line 1)

In [21]:
print(t2[1,2])

26679


In [28]:
print(t2)
print(t2[1:4,1:5])  # 取多行多列

[[4394029  320053    5931   46245]
 [7860119  185853   26679       0]
 [5845909  576597   39774  170708]
 ...
 [ 142463    4231     148     279]
 [2162240   41032    1384    4737]
 [ 515000   34727     195    4722]]
[[185853  26679      0]
 [576597  39774 170708]
 [ 24975   4542  12829]]


## 6.numpy数值修改和布尔索引|

In [31]:
t3 = np.arange(24).reshape(4,6)

In [32]:
t3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [33]:
t3<10

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [35]:
t3[t3<10] = 10
t3

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [38]:
np.where(t3<=10,0,10)

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [42]:
print(t3.clip(10,18))  # <10变成10 >18变成18
print(t3)

[[10 10 10 10 10 10]
 [10 10 10 10 10 11]
 [12 13 14 15 16 17]
 [18 18 18 18 18 18]]
[[10 10 10 10 10 10]
 [10 10 10 10 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


## 7.nan和inf
### nan的特性
1. 两个nan不相等 `np.nan != np.nan`
2. 任何值与nan计算都是nan


In [43]:
np.nan != np.nan

True

In [44]:
t4 = np.arange(24).reshape(4,6)

In [45]:
t4 = t4.astype("float")

In [46]:
t4

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [49]:
t4[2,3]='nan'
t4

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., nan, 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [51]:
np.count_nonzero(t4)

23

In [52]:
np.count_nonzero(t4!=t4)  # 统计nan的个数

1

In [54]:
np.count_nonzero(np.isnan(t4))

1

In [57]:
t4[np.isnan(t4)]=0
t4

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14.,  0., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

## 8.numpy中的常用统计函数

### 8.1 求和

In [63]:
np.sum(t4, axis=0)  # 每一列
np.sum(t4, axis=1)  # 每一行

array([ 15.,  51.,  72., 123.])

In [62]:
np.sum(t4[1,])  # 第2行

51.0

### 8.2 均值


In [64]:
np.mean(t4[0,])

2.5

### 8.3 中值

In [65]:
np.median(t4[0,])

2.5

### 8.4 最大值

In [66]:
np.max(t4)

23.0

### 8.5 最小值

In [67]:
np.min(t4)

0.0

### 8.6 极值

In [68]:
np.ptp(t4)

23.0

### 8.7 标准差

In [69]:
np.std(t4)

7.247485196029493

## 9. numpy中nan的替换

In [70]:
t8 = np.arange(12).reshape(3,4).astype("float")

In [71]:
t8[1,2:]=np.nan

In [72]:
t8

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5., nan, nan],
       [ 8.,  9., 10., 11.]])

In [78]:
def fill_ndarray(t8):
    for i in range(t8.shape[1]):
        temp_col = t8[:,i]  # 取一列
        nan_num = np.count_nonzero(temp_col!=temp_col)  # 计算这一列nan的个数
        if nan_num !=0:  
            temp_not_nan_col = temp_col[temp_col==temp_col]  # 取出不是nan的元素
            temp_col[np.isnan(temp_col)] = np.mean(temp_not_nan_col)  # 计算平均值并替换
    return t8

In [77]:
fill_ndarray(t8)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])