In [1]:
from numpy import * as np

SyntaxError: invalid syntax (<ipython-input-1-157140e7bde7>, line 1)

In [2]:
import numpy as np

In [3]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


# 这是numpy学习笔记


## 1.数组的创建

In [ ]:
# a = np.array([1, 2, 3])

In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
a1 = np.arange(15)

In [8]:
print(type(a1))
print(a1)

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [9]:
print(a1.dtype)

int32


In [10]:
a2 = np.array(range(10), dtype="i8")

In [11]:
print(a2.dtype)

int64


In [12]:
a3 = np.array([1,0,1,0,1,0],dtype="bool" )  # 指定类型

In [13]:
print(a3)

[ True False  True False  True False]


In [14]:
a4 = a3.astype("int8")  # 调整类型

In [15]:
print(a4)

[1 0 1 0 1 0]


In [16]:
a5 = np.array([random.random() for i in range(10)])  # 生成小数数组

In [17]:
print(a5)

[0.30624354 0.15805669 0.24917197 0.15848761 0.52974618 0.27012424
 0.42383294 0.32721137 0.47537906 0.49577152]


In [18]:
a6 = np.round(a5, 2)  # 取小数点后两位

In [19]:
print(a6)

[0.31 0.16 0.25 0.16 0.53 0.27 0.42 0.33 0.48 0.5 ]


## 2.数组的形状

In [1]:
t1 = np.arange(10)

NameError: name 'np' is not defined

In [2]:
import numpy as np


In [3]:
t1 = np.arange(10)  # 一维数组

In [4]:
t1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
t1.shape

(10,)

In [6]:
t2 = np.array([[1,2,3],[4,5,6]])  # 二维数组

In [7]:
t2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
t2.shape

(2, 3)

In [9]:
t3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])  # 三维数组

In [10]:
t3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [11]:
t3.shape

(2, 2, 3)

In [12]:
t4 = np.arange(12)

In [13]:
t4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
t4.reshape(3,4)  # 调整数据形状

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
t5 = np.arange(24).reshapeh(2,3,4)

AttributeError: 'numpy.ndarray' object has no attribute 'reshapeh'

In [20]:
t5 = np.arange(24).reshape((2,3,4))

In [21]:
t5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [19]:
t5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [22]:
t5.reshape((24,)) # shape中有几个值就是几维

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
t5.reshape((24,1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [24]:
t5.reshape((1,24))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [25]:
t5.shape[0]

2

In [26]:
t5 = t6.reshape((3,4))

NameError: name 't6' is not defined

In [29]:
t5 = t5.reshape((4,6))
t5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [30]:
t5.flatten()
t5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [31]:
t5.flatten()  # 展开数组成一维数组


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## 3.数组的计算

In [33]:
t5+2

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25]])

In [35]:
t5/0  # 不会报错 nan:not a number  inf: infinity


E:\Aoconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
E:\Aoconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [36]:
t6 = np.arange(100,124).reshape((4,6))
t6

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123]])

In [37]:
t5+t6


array([[100, 102, 104, 106, 108, 110],
       [112, 114, 116, 118, 120, 122],
       [124, 126, 128, 130, 132, 134],
       [136, 138, 140, 142, 144, 146]])

In [39]:
t7 = np.arange(6)
t7

array([0, 1, 2, 3, 4, 5])

In [40]:
t5-t7

array([[ 0,  0,  0,  0,  0,  0],
       [ 6,  6,  6,  6,  6,  6],
       [12, 12, 12, 12, 12, 12],
       [18, 18, 18, 18, 18, 18]])

In [41]:
t8 = np.arange(4).reshape((4,1))
t8

array([[0],
       [1],
       [2],
       [3]])

## 4.数组转置 

In [50]:
t5.shape



(4, 6)

In [53]:
t5=t5.transpose()
t5.shape

(6, 4)

In [54]:
t5 = t5.T
t5.shape

(4, 6)

In [ ]:
t5 = t5.swapaxes(1,0)
t5.shape

## 5.numpy读取数据:
```np.loadtxt(frame.dtype=np.float.delimiter=None,skiprows=0,usecols=None,unpack=False)```




| 参数 | 解释 |
|--|--|
| frame    | 文件，字符串，产生器，可以是.gz或.bz2压缩文件 |
| dtype    | 数据类型，可选，CSV的字符以什么数据类型读入数组中，默认np.float |
| delimiter | 分离字符串,默认是任何空格,改为逗号|
| skiprows  | 跳过前x行,一般跳过表头 |
| usecols   | 读取指定的列,索引,元组类型 |
| unpack   | 如果是True,读入属性将分别写入不同的数组变量,False读入数据只写入一个数组变量,默认False |


In [42]:
import numpy as np

In [46]:
us_file_path = "./youtube_video_data/US_video_data_numbers.csv"
uk_file_path = "./youtube_video_data/GB_video_data_numbers.csv"
t1 = np.loadtxt(us_file_path,delimiter=",")
print(t1)

[[4.394029e+06 3.200530e+05 5.931000e+03 4.624500e+04]
 [7.860119e+06 1.858530e+05 2.667900e+04 0.000000e+00]
 [5.845909e+06 5.765970e+05 3.977400e+04 1.707080e+05]
 ...
 [1.424630e+05 4.231000e+03 1.480000e+02 2.790000e+02]
 [2.162240e+06 4.103200e+04 1.384000e+03 4.737000e+03]
 [5.150000e+05 3.472700e+04 1.950000e+02 4.722000e+03]]


In [47]:
t1 = np.loadtxt(us_file_path,delimiter=",", dtype="int")
print(t1)

[[4394029  320053    5931   46245]
 [7860119  185853   26679       0]
 [5845909  576597   39774  170708]
 ...
 [ 142463    4231     148     279]
 [2162240   41032    1384    4737]
 [ 515000   34727     195    4722]]


In [48]:
t1 = np.loadtxt(us_file_path,delimiter=",", dtype="int",unpack=True)
print(t1)

[[4394029 7860119 5845909 ...  142463 2162240  515000]
 [ 320053  185853  576597 ...    4231   41032   34727]
 [   5931   26679   39774 ...     148    1384     195]
 [  46245       0  170708 ...     279    4737    4722]]
